image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  COMPOSE_INTERACTIVE_NO_CLI: 1
  DEPLOY_ENV: 1
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

build:
  script:
    - docker-compose up -d postgres
    - docker-compose up server