image: docker

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  SERVER_NAME: 'discussions-server'

stages:
#  - test
  - build

#test:
#  stage: test
#  script:
#    - apk update
#    - apk upgrade
#    - rm -rf .gitmodules
#    - mv .gitmodules-ci .gitmodules
#    - apk add git
#    - git submodule update --init --recursive
#    - apk add python python-dev py-pip build-base libffi-dev openssl-dev libgcc
#    - pip install --no-cache-dir docker-compose~=1.23.0
#    - docker-compose -f docker-compose-ci.yml up -d arangodb postgres
#    - docker-compose -f docker-compose-ci.yml run server sh -c "mvn test"


build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -f ./docker/production/Dockerfile -t $CI_REGISTRY_IMAGE:$SERVER_NAME .
    - docker push $CI_REGISTRY_IMAGE:$SERVER_NAME