image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  COMPOSE_INTERACTIVE_NO_CLI: 1
  DEPLOY_ENV: 1

before_script:
  - apk update
  - apk upgrade
  - rm -rf .gitmodules
  - mv .gitmodules-ci .gitmodules
  - apk add git
  - git submodule update --init --recursive
  - apk add python python-dev py-pip build-base
  - pip install docker-compose

build:
  script:
    - docker-compose -f docker-compose-ci.yml up -d arangodb postgres
    - docker-compose -f docker-compose-ci.yml run server sh -c "mvn test && mvn checkstyle:check"
