version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: docker/nginx
    ports:
      - 80:80

  rabbit:
    restart: always
    image: rabbitmq:3.7.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672

  cassandra:
    restart: always
    image: cassandra
    volumes:
      - ./cassandra-data/:/var/lib/cassandra

  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=gitrekt_quora
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app
    command: "sh -c \"./watch.sh\""
    env_file:
      - .env
