version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: docker/nginx
    ports:
      - 80:80

  rabbit:
    restart: always
    image: rabbitmq:3.7.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672

  arangodb:
    restart: always
    image: arangodb:latest
    volumes:
      - ./arangodb-data/:/var/lib/arangodb3
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=root

  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379

  postgres:
    restart: always
    image: postgres
    build:
      dockerfile: ./docker/postgres/Dockerfile
      context: .
    environment:
      - POSTGRES_DB=gitrekt_quora
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - gitrekt
    volumes:
      - ./postgres-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    networks:
      - gitrekt
    environment:
      - QUEUE_NAME=questions-v1-queue
      - RABBIT_HOST=rabbit
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app
    command: "sh -c \"./watch.sh\""

networks:
  gitrekt:
    external:
      name: starterserver_gitrekt
