version: "3"
services:
  proxy:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
    ports:
      - 80:80

  mainserver:
    build:
      dockerfile: ./Dockerfile
      context: .
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app
    command: "mvn exec:java"
