version: "3"
services:
  user-auth-server:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app
    command: "sh -c \"./watch.sh\""
    networks:
      - dev-conf_gitrekt-network
    env_file:
      - .env

networks:
  dev-conf_gitrekt-network:
    external: true